CREATE TABLE plans (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    price_month DECIMAL(10,2) NOT NULL DEFAULT 0.00,

    max_companies INT UNSIGNED NOT NULL DEFAULT 1,
    max_users INT UNSIGNED NOT NULL DEFAULT 1,
    storage_limit_mb INT UNSIGNED NOT NULL DEFAULT 1024,

    is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;